docs/run.md, tests/e2e.sh
Fixed by https://github.com/kubernetes-sigs/kustomize/pull/2165
=> Remove workaround for 'fn run' scoping.

ts/create-kpt-functions/package-lock.json, ts/create-kpt-functions/package.json, ts/create-kpt-functions/src/cli.ts
=> Set exit code on exceptions thrown in the CLI

.github/workflows/ci.yaml
Successful run here: https://github.com/prachirp/kpt-functions-sdk/pull/3/checks?check_run_id=504215406
=> Add shell-ci github action job

ts/kpt-functions/src/run.ts
Also controlled through STRUCTURED_RESULTS env var.
To maintain current behavior, this is false by default.
=> Feature flag structure results using --structured_results.

tests/e2e.sh, ts/demo-functions/build/helm_template.Dockerfile, ts/demo-functions/package-lock.json, ts/demo-functions/src/helm_template.ts, ts/demo-functions/src/helm_template_run.ts, ts/demo-functions/src/helm_template_test.ts
Addresses https://github.com/GoogleContainerTools/kpt/issues/586
=> Helm template typescript function

ts/create-kpt-functions/package.json
Addressing https://github.com/GoogleContainerTools/kpt/issues/561
=> Use typegen 0.17.0 in the CLI

ts/demo-functions/build/kubeval.Dockerfile, ts/demo-functions/src/kubeval.ts, ts/demo-functions/src/kubeval_run.ts, ts/demo-functions/src/kubeval_test.ts
As discussed with @prachirp over email, we're interested in contributing our kubeval kpt function upstream!  It took a bit longer than expected because we wanted to ensure that we were staying compatible with the latest kpt-functions version, and also considered porting the function to Golang, given the improved SDK support for that.
This is a starting point, and I think we are definitely still open to porting the function to Golang or make other improvements as long as it stays API compatible
=> Add a basic demo function using kubeval

ts/demo-functions/build/annotate_config.Dockerfile, ts/demo-functions/src/annotate_config.ts, ts/demo-functions/src/annotate_config_run.ts, ts/demo-functions/src/annotate_config_test.ts
=> Add annotate config demo function

ts/kpt-functions/package-lock.json, ts/kpt-functions/src/run.ts
Re-generate package-lock.json.
Fixes https://github.com/GoogleContainerTools/kpt/issues/696
=> Fix type ambiguity in run.ts

ts/kpt-functions/package-lock.json, ts/kpt-functions/package.json, ts/kpt-functions/src/types.ts, ts/kpt-functions/src/types_test.ts
Fixes GoogleContainerTools/kpt#803
=> Fix when missing functionConfig

ts/kpt-functions/package-lock.json, ts/kpt-functions/package.json, ts/kpt-functions/src/metadata.ts, ts/kpt-functions/src/testing_test.ts, ts/kpt-functions/src/types.ts, ts/kpt-functions/src/types_test.ts
=> Print field in results and update version

MAINTAINERS
=> add Donny Xia to maintainer

ts/create-kpt-functions/templates/func.mustache
Ref: https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/198
=> update usage doc template

example-configs/audit/rolebinding_viewers.yaml, example-configs/clusterrole_namespace-reader.yaml, example-configs/clusterrole_pod-creator.yaml, example-configs/clusterrolebinding_namespace-readers.yaml, example-configs/customresourcedefinition_fulfillmentcenters.foo-corp.com.yaml, example-configs/gatekeeper.yaml, example-configs/payments-team.yaml, example-configs/podsecuritypolicy_psp.yaml, example-configs/shipping-dev/rolebinding_job-creators.yaml, example-configs/shipping-dev/rolebinding_pod-creators.yaml, example-configs/shipping-dev/rolebinding_viewers.yaml, example-configs/shipping-prod/rolebinding_pod-creators.yaml, example-configs/shipping-prod/rolebinding_sre-admin.yaml, example-configs/shipping-prod/rolebinding_viewers.yaml, example-configs/shipping-staging/rolebinding_pod-creators.yaml, example-configs/shipping-staging/rolebinding_viewers.yaml
Formats example configs to avoid unwanted diffs. https://github.com/GoogleContainerTools/kpt/issues/2068
=> Format examples configs

ts/create-kpt-functions/package-lock.json, ts/create-kpt-functions/package.json, ts/create-kpt-functions/src/utils/validator.ts, ts/demo-functions/package-lock.json, ts/demo-functions/package.json, ts/demo-functions/src/annotate_config.ts, ts/kpt-functions/package-lock.json, ts/kpt-functions/package.json, ts/kpt-functions/src/io_test.ts, ts/kpt-functions/src/run.ts
Snyk can't simply update the version since it requires reformat the source code.
=> upgrade prettier

ts/kpt-functions/package-lock.json, ts/kpt-functions/package.json
Tried to follow the process in https://github.com/GoogleContainerTools/kpt-functions-sdk/pull/338/files
=> kpt-functions@0.14.6-rc.0

tests/e2e.sh, ts/demo-functions/package-lock.json, ts/demo-functions/package.json, ts/demo-functions/test-data/intermediate/foo.yaml, ts/hello-world/package-lock.json, ts/hello-world/package.json, ts/init-package/package-lock.json, ts/init-package/package.json
Following release process in https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/master/CONTRIBUTING.md#kpt-functions
=> Update deps to use kpt-functions@0.16.0-rc.0

ts/kpt-functions/package-lock.json, ts/kpt-functions/package.json
Following release process at https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/master/CONTRIBUTING.md#kpt-functions
=> kpt-functions@0.16.0

ts/demo-functions/package-lock.json, ts/demo-functions/package.json, ts/hello-world/package-lock.json, ts/hello-world/package.json, ts/init-package/package-lock.json, ts/init-package/package.json
Following release process https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/master/CONTRIBUTING.md#kpt-functions
=> Update deps to use kpt-functions@0.16.0

ts/kpt-functions/src/run.ts, ts/kpt-functions/src/run_test.ts
The logic is the same as what we do in kyaml, but in typescript.
=> ensure output annotation format match input

ts/kpt-functions/src/io_test.ts, ts/kpt-functions/src/result_test.ts, ts/kpt-functions/src/types.ts
To be consistent with the KRM function spec
=> rename suggestedValue to proposedValue

ts/kpt-functions/src/types.ts, ts/kpt-functions/src/types_test.ts
This API is intended to provide a consistent functionality for
sorting function results. The sorting behavior is based on the
functionality of the Sort implementation in the golang function sdk.
Issues: GoogleContainerTools/kpt#2195
The golang SDK implementation can be seen here: https://github.com/kubernetes-sigs/kustomize/pull/4325
=> feat: add sortResults function

go/fn/examples/example_filter_GVK_test.go, go/fn/object.go
Merge after https://github.com/GoogleContainerTools/kpt-functions-sdk/pull/526
This is a convenient function.
=> Add IsGVK func

go/fn/internal/map.go, go/fn/object.go, go/fn/resourcelist.go, go/fn/subobject.go, go/fn/subobject_test.go
This allows for reading / passing-around arbitrary subobjects.
=> Introduce abstraction for subobjects

go/fn/internal/map.go, go/fn/run.go
When unknown panic happens,  we shall let it fail with the stack trace.
=> Panic with stack trace

go/fn/resourcelist.go
Introduced by merging conflict in https://github.com/GoogleContainerTools/kpt-functions-sdk/pull/570
The code has a "clean" non-overlapping conflict, but the logic is changed.
=> fix: parseResourceList should not return until finish parsing results. 

.github/workflows/release-typegen.yaml
It seems Github Action doesn't support full semver
=> update setup-gcloud github action version

go/fn/object.go, go/fn/object_test.go
to allow wildcard matching for group and version separately instead of apiVersion
=> change IsGVK

go/fn/object.go, go/fn/object_test.go
Current the Nested functions can set slice of some simple struct such as map or string. `setSlice` allow users to set set a slice of SubObject.
=> add `setSlice` function

go/fn/object.go, go/fn/object_test.go
Kudos to @kispaljr who found the issue and provides the fixes. related to https://github.com/GoogleContainerTools/kpt/issues/3931
=> fix NestedSubObject

CODEOWNERS, LICENSE-documentation, MAINTAINERS, README.md
Adding a MAINTAINERS file
Update CODEOWNERS
Update README
Update documentation license.
=> Update governance things
