- .github/workflows/mirror-functions.yaml
- scripts/mirrorImages.sh
- Triggers on push to all branches in order to validate workflow
- GCP_SA_EMAIL service account must have Storage Admin permissions to push images to project's registry, needs to be validated
> Add workflow to mirror functions

- docs/develop.md
- scripts/init-package.sh
- scripts/kind-config.yaml
Instructions no longer work on GCP for 1.14. These require alpha
features to be enabled, but there is a conflict with alpha features that
causes the API Server to generate an incomplete swagger.json.
Surfacing CRDs in the OpenAPI Spec is beta in 1.15 and automatically
activated, so using 1.15 works.
DOES NOT WORK IN GCP WITH ALPHA FEATURES ENABLED, FOR ANY VERSION.
> Modify instructions to specify Kubernetes 1.15

- .gitignore
Mac OS automatically creates .DS_Store files in all directories so configure .gitignore to ignore such files.
> Ignore Mac .DS_Store files

- .github/workflows/ci.yaml
Fix the go-ci workflow because its Build, Test, Lint step fails in forks of this project.
This is because the workflow checks out code into go/src/github.com/${{ github.repository }} while our go code imports from go/src/github.com/GoogleContainerTools/kpt-functions-sdk/...
Hardcode this path in the workflow so it will still pass in forks.
> Fix go-ci workflow

- .gitignore
- ts/demo-functions/src/validate_rolebinding.ts
- ts/kpt-functions/src/errors.ts
- ts/kpt-functions/src/errors_test.ts
- ts/kpt-functions/src/io.ts
- ts/kpt-functions/src/io_test.ts
- ts/kpt-functions/src/run.ts
- ts/kpt-functions/src/types.ts
- Add `.issues` to `ResourceList`
- Add `toIssues()` methods to ConfigError and its subclasses
- Add `--log-to-stderr` that optionally logs config issues to stderr. This is a change in behavior.
> Enable functions to return structured results.

- ts/kpt-functions/src/testing.ts
Test expected output even in failure case.
Make 'unchanged' assertion explicit.
https://github.com/GoogleContainerTools/kpt/issues/583
> Minor refactoring Testing util.

- ts/kpt-functions/src/io.ts
- ts/kpt-functions/src/io_test.ts
cc @phanimarupaka @frankfarzan 
Increase line width to 120 as a workaround for https://github.com/GoogleContainerTools/kpt/issues/685
> Unset line width to allow arbitrarily long lines

- ts/kpt-functions/src/io_test.ts
- ts/kpt-functions/src/result_test.ts
- ts/kpt-functions/src/types.ts
This is one half of the work needed to support arbitrary value suggestions.  I will follow up with a PR to kustomize as well if needed.  Closes https://github.com/GoogleContainerTools/kpt/issues/747.
> Add support for any JSON type when suggesting values in Results

- ts/create-kpt-functions/src/cmd/type_create.ts
@frankfarzan @prachirp 
This is a follow up PR to https://github.com/GoogleContainerTools/kpt-functions-sdk/pull/160. 
Users can choose source for the types either from built-in or kubeconfig. Here is the question
```
Kubernetes Types used to generate Typescript library (0) +
[0] Use built-in types (No cluster required)? +
[1] Select a context from kubeconfig ? +
Please enter your numeric choice: 
```
Based on answer to this question, the next question to choose the context follows if choice is [1].
> Type gen from sources

- ts/kpt-functions/src/io.ts
- ts/kpt-functions/src/io_test.ts
- ts/kpt-functions/src/types.ts
Avoid using YAML refs because many YAML parsers in the k8s ecosystem don't support them.
Without this change, a typical output from a kpt fn run might look like this:
```yaml
apiVersion: v1
kind: ResourceList
metadata:
name: output
items:
- apiVersion: v1
kind: Foo
metadata:
name: bar
spec:
array: &ref_0
- &ref_1
baz: 1
results:
- message: something is wrong
severity: error
resourceRef:
apiVersion: v1
kind: Foo
namespace: ''
name: bar
file: {}
field:
path: spec.array
currentValue: *ref_0
suggestedValue:
- *ref_1
- baz: 3
```
The usage of `&ref_0` and `*ref_0` breaks many YAML parsers that don't implement that YAML feature.
> Avoid emitting YAML back-references in kpt fn output

- ts/demo-functions/package-lock.json
- ts/demo-functions/package.json
- ts/demo-functions/src/validate_rolebinding_test.ts
- ts/demo-functions/src/write_yaml_test.ts
This PR contains the change from #215.
It appears that some test were broken with #215. This PR upgrades jasmine and fixes the broken tests.
> Upgrade jasmine from 3.5.0 to 3.6.3 and fix broken tests

- ts/kpt-functions/src/testing.ts
We are using the TestRunner to test our own kpt functions. For our use-cases, we have found the output of failed test cases to be insufficient in helping us locate the actual problems. That is because the test assertion compares two rendered YAMLs. These YAML strings are simply too long and the testing library (jasmine) truncates the strings, typically before the actual difference has appeared.
With this change, we compare JavaScript objects instead, and the assertion errors show a vastly improved structural diff between the configs. Now, we have been careful here to not change the behavior in terms of when tests succeed or fail. We've done that by still converting the configs to YAML and then converting them back from YAML. For us, this has been working exactly as intended.
@emmmile
Both …
> Structurally compare js objects rather than YAML

- ts/create-kpt-functions/src/cmd/docker_create.ts
- ts/create-kpt-functions/templates/package.json.mustache
We fall back to the legacy one if the new one can't be found.
Fixes: https://github.com/GoogleContainerTools/kpt/issues/1394
> Use config.docker_repo_base instead of kpt.docker_repo_base in package.json

- ts/kpt-functions/src/gen/io.k8s.api.core.v1.ts
- ts/kpt-functions/src/gen/io.k8s.apimachinery.pkg.api.resource.ts
- ts/kpt-functions/src/gen/io.k8s.apimachinery.pkg.apis.meta.v1.ts
- ts/kpt-functions/src/gen/io.k8s.apimachinery.pkg.runtime.ts
- ts/kpt-functions/src/gen/io.k8s.apimachinery.pkg.util.intstr.ts
- ts/kpt-functions/src/gen/io.k8s.apimachinery.pkg.version.ts
- ts/kpt-functions/src/metadata.ts
- ts/kpt-functions/src/result.ts
- ts/kpt-functions/src/result_test.ts
- ts/kpt-functions/src/run.ts
- ts/kpt-functions/src/run_test.ts
We record the original annotations value before invoking the function
And we compare the recorded values with the annotations after modification
to infer the user's intend.
Tests will be added soon.
> Support internal.config.kubernetes.io annotations

- ts/kpt-functions/src/metadata.ts
The prefix of the legacy id annotation is slightly different from the others. This PR updates it to the right one.
Ref: https://github.com/kubernetes-sigs/kustomize/issues/4024
This PR will need to be on top of https://github.com/GoogleContainerTools/kpt-functions-sdk/pull/450 to have the CI passing.
> update the legacy id annotation name to the right one

- ts/create-kpt-functions/src/cmd/package_create.ts
The init kpt-functions command was always printing the default,
regardless of whether an input was provided. This fixes the behavior to
print the proper value.
fixes: GoogleContainerTools/kpt#2527
> fix: print correct container registry on init

- go/fn/errors.go
- go/fn/examples/example_builtin_function_test.go
- go/fn/examples/example_filter_GVK_test.go
- go/fn/examples/example_generator_test.go
- go/fn/examples/example_logger_injector_test.go
- go/fn/examples/example_mutate_comments_test.go
- go/fn/examples/example_read_field_test.go
- go/fn/examples/example_read_functionConfig_test.go
- go/fn/examples/example_set_field_test.go
- go/fn/examples/example_validator_test.go
- go/fn/resourcelist.go
- go/fn/run.go
Discovered the root cause of https://github.com/GoogleContainerTools/kpt/issues/2901
In the function SDK `Run` function, the error returned by `Process` is not returned back to `AsMain`. As a result, the function executes "successfully" and kpt does not report the function failure.
In the function SDK `AsMain` function, if `Run` returns an error, we do not get the results from the ResourceList because the ResourceList is not written back to stdout.
This PR fixes the problem in the SDK. 
I have another PR (https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/782) that fixes the problem in apply-replacements.
Before: 
```
Package "apply-replacements-error": 
[RUNNING] "gcr.io/kpt-fn/apply-replacements:unstable"
[PASS] "gcr.io/kpt-fn/apply-replacements:unstable" in 1.1s …
```
> sdk.AsMain should return fn error

- go/fn/examples/example_generator_test.go
- go/fn/examples/example_test.go
- go/fn/object.go
- go/fn/subobject.go
This PR proposes two user patterns:
-  a concatenated type-specific get
-  a similar experience as using [`unstructured.Unstructured`](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured#NestedStringMap)  `NestedXXX`
User pattern #1:
```go
// o is KubeObject of KCC resource apiVersion: serviceusage.cnrm.cloud.google.com, kind: Service
externalString := o.GetMap("spec").GetMap("projectRef").GetString("external")
}
```
User pattern #2
```go
// o is KubeObject of KCC resource apiVersion: serviceusage.cnrm.cloud.google.com, kind: Service
externalString := o.NestedString("spec", "projectRef", "external")
}
``` 
- Added type support for int64, float64, boolean, map
- Change `GetXXX(fields... string)` to  `NestedXXX(fields...string)`
- Add `NestedXXXOrDie` to handle bad type …
> Use go sdk like unstructured.Unstructured 

- go/fn/run.go
Ref: https://github.com/kubernetes-sigs/kustomize/blob/22b735885a5ed4e038b9c8e98fc261cd39d96193/kyaml/kio/byteio_reader.go#L32-L34
> fn sdk should not try to set id annotations

- go/fn/resourcelist.go
- go/fn/resourcelist_test.go
- go/fn/run.go
This function can be used after function evaluation to make sure the change won't introduce duplicate resource. 
See usage here https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/844/files#diff-2b0b1f52afe9e1c4943996b7c2f696f3b641bfc6e0e5beef48d273e72b2b9d19R43
> Check resource duplication by GVKNN

- go/fn/internal/map.go
- go/fn/object.go
- go/fn/object_test.go
- go/fn/resourcelist.go
Instead of using a YNode `NodeTagNull` tag, we use an empty `MapNode` YNode. This saves the krm resource level `IsNull` check.
This PR allows KRM fn to parse, call and modify empty function config.  
- `parseResourceList` always initialize functionConfig to `KubeObject` even if the functionConfig is empty.  
- Reason: from krm fn author side, the functionConfig should be considered as a KRM resource.
- Usage: From users side, they can check whether a functionConfig is empty via `resourceslist.functionConfig.IsDummy()` 
- A special KubeObject is introduced, which `internal.MapVariant` is referring to a  `NodeTagNull` YNode.
- Reason: empty functionConfig can use this Dummy `KubeObject` and smoothly get KRM specific info like typeMeta and nameMeta via `GetKind` `GetNamespace` …
> Initialize resourcelist.functionConfig even if it's empty.

- starlark/get-started/data/resources.yaml
- starlark/get-started/starlark-fn-config.yaml
both Go SDK and starlark SDK user guide will use the get-started examples in the kpt-function-sdk repo.
> Add get-started code as starlark SDK user guide sample code

- go/get-started/Dockerfile
- go/get-started/README.md
- go/get-started/data/resources.yaml
- go/get-started/main.go
This PR adds a `go/get-started` directory, which is used by the GO SDK kpt.dev book as starting point to write functions.
> Add get-started code as go SDK user guide sample code

- go/fn/examples/example_read_field_test.go
- go/fn/object.go
- go/fn/object_test.go
- go/fn/subobject.go
- Add functions `NestedStringMapOrDie` , `NestedStringSliceOrDie`, `SetNestedStringOrDie`,  `SetNestedStringMapOrDie`,  `SetNestedStringMapOrDie`,  `SetNestedStringSliceOrDie`. This gives go SDK users an easier approach to get/set string specific fields like what unstructured.Unstructured does. 
- Note: Users shall not get/set interface{} directly from go SDK, but should use `SubObject` or `SliceSubObjects` (A slice of `SubObject`) to make more complicated struct operations. 
- Fix `GetMap` which didn't add the YNode content to the returned `SubObject`
- Add examples for KubeObject operations in two styles: 
-  `GetMap`
-  `unstructured.Unstructured`
- Add test coverage for KubeObject/SubObject `Get`/`Set`
> feat: Complete the types for NestedFields Set/Get

- go/fn/const.go
- go/fn/errors.go
- go/fn/go.mod
- go/fn/go.sum
- go/fn/object.go
- go/fn/object_test.go
- go/fn/origin.go
- go/fn/origin_test.go
- go/fn/run.go
Related issue: https://github.com/GoogleContainerTools/kpt/issues/3292
Design doc here: https://docs.google.com/document/d/1YwxalwS45V1BhvzwWrgHJQPL2mZ1xchIzTm_eI6jXsk/edit#
This PR contains 3 features:
- Define our own `ResourceIdentifier` (so we do not import kustomize nor apimachinery) 
- Add two methods to return current identifier `GetId` and upstream identifier `GetOriginId`. original-id is the upstream identifier, which should be in the form of `group|kind|namespace|name`. 
-  Group allows empty "" for core v1 resources
- Namespace allows `~C` for cluster scoped and unknown scoped resource, `default` for namespace scoped but not specified value.
- Block methods that can change upstream-identifier annotation.  (there's a `SetOrDie` that I haven't changed in this PR, I plan to remove …
> Support identifier annotation

- go/fn/internal/map.go
- go/fn/internal/test/variant_test.go
Using NewFromTypedObject for e.g. a k8s Deployment resource fails. The reason for this is that the sortFields function in internal/maps expects the map to contain only scalar values or mapping type entries. Sequence/Slices entries lead to an error when the length of the node count is checked for sorting.
65b4725 adds a corresponding test that yields without the fix
```
variant_test.go:214:
Error Trace:    variant_test.go:214
Error:          Received unexpected error:
unable to sort fields in yaml: invalid number of nodes: 1
Test:           TestTypedObjectToMapVariant
```
cbc48fb fixes this by only sorting yaml nodes of the mapping types. If a Sequence type is encountered its entries are checked regarding whether they are of the mapping type to sort them if so.
> fix: sortField for map/slice combination

- go/fn/examples/example_asmain_runner_test.go
- go/fn/examples/example_logger_injector_test.go
- go/fn/functionrunner.go
- go/fn/object_test.go
- go/fn/origin_test.go
- go/fn/run.go
- Update Runner interface to use `KubeObjects` which now supports the `Where` `WhereNot` filter functions
- Allow `AsMain` to accept both the `Runner` instance and the pointer to improve user experience.
> fix: Improve Runner user experience

- go/fn/const.go
- go/fn/examples/go.mod
- go/fn/examples/go.sum
- go/fn/go.mod
- go/fn/go.sum
- go/fn/internal/test/go.mod
- go/fn/internal/test/go.sum
- go/fn/object.go
- go/fn/object_test.go
This PR extends the `items *kubeObjects` selector to get the root Kptfile. 
The root Kptfile contains the variant constructor values like pkg name. One pattern we found in the app config and from user feedback is to use some Kptfile or certain input resource fields as the function config value. 
I plan to use this method in the set-default-label. Later on, we can provide more selector functions to filter custom GVK resources . 
@justinsb @mengqiy
> Add function `GetRootKptfile`

- go/fn/object.go
- go/fn/object_test.go
`isLocalConfig` is a method of `KubeObject`. Because this usage often comes with `Where` and `WhereNot` functions to work as filters, and `Where` needs a function input, I refactored a function that provides the same logic as the method to facilitate the usage.
> fix: `isLocalConfig`, add function besides original method

- go/fn/result.go
The original `Result` contains field `ResourceRef`, it uses `ResourceIdentifier` inside kyaml package instead of sdk's own definition of ResourceIdentifier. Here I change it to be the format of sdk. Because when I use sdk package to write curated functions, I want to log the results without using kyaml package.
> fix: modify result without kyaml package

- go/fn/object.go
Encourage IsGroupVersionKind or IsGroupKind instead.
> Deprecate IsGVK, as the matching semantics are surprising

- go/fn/context.go
- go/fn/examples/example_asmain_runner_test.go
- go/fn/functionrunner.go
- go/fn/result.go
- go/fn/run.go
- go/fn/runnerProcessor.go
This PR does 3 jobs
- It adds `Results` methods.
- It allow Context to control the flow.
- It split `results` from previous `context`
> Add `Results` method and `Context`

- go/fn/object.go
This is used when parsing a multi-object yaml document.
> Add ParseKubeObjects helper to parse multiple objects

- go/fn/runnerProcessor.go
- go/fn/runnerprocessor_test.go
Some major changes
- This PR better handles the `reflect` based operations:
-  avoid panic if non pointer object is used
- Specifically requires a `map[string]string` argument from the `Runner` object, and assigns the `ConfigMap.data` to it. Previously, it assigns the `ConfigMap.data` to the first struct type object, which could be problematic.
- Check whether a field can be set before assigning the value.
- This PR handles a risk condition where users do not provide the a `FunctionConfig` object but kpt creates a placeholder and adds it to ResourceList, previously we could not tell whether the FunctionConfig is from users or kpt and thus cannot guide users helpful information on whether a fnConfig is missing or misconfigured. This PR adds a check specifically for the kpt generated …
> Validate FnRunner workflow

- go/fn/object.go
- go/fn/run.go
- go/fn/testhelpers/golden.go
This PR add methods in `go/fn/testhelper` to let function authors to test their code easily.
Users should write the input data in a new directory, write the function config in a file named `_fnconfig.yaml`, and write the expected output in a file named `_expected.yaml`. Then use the `testhelper` functions to read the input, run tests and compare with the expected data. 
This idea is developed from the Wow demo, borrowed some methods and naming conventions from https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/926 and I rewrote the methods using the latest go SDK methods.
I uploaded an example [in this PR](https://github.com/GoogleContainerTools/kpt-functions-sdk/pull/602), which I plan to provide to function authors as [kpt scaffolding …
> Add test infra for KRM functions SDK

- .github/workflows/ci.yaml
- Makefile
- go/Makefile
- go/fn/examples/data/setlabels-resourcelist.yaml
- go/fn/examples/example_select_exclude_test.go
- go/fn/internal/namespace.go
- go/fn/object_test.go
- go/fn/resourcelist_test.go
- go/fn/runnerProcessor.go
- go/fn/runnerprocessor_test.go
- go/fn/testhelpers/golden.go
- go/get-started/data/resources.yaml
- go/get-started/main.go
- hack/ci-validate-go.sh
Problem: Previous CI checks the license and gofmt but does not raise the error to users  (it just outputs the files as unstaged and then abandoned them). 
This PR does 3 fixes
- Added the missing CopyRight
- Fixed the go fmt
- Added a generate.sh which checks the license and gofmt are all commited; Update the CI to rely on the generate.sh to pass/fail the check.
> Update ci to validate gofmt

- ts/typegen/cmd/main.go
- ts/typegen/swagger/arrays.go
- ts/typegen/swagger/language/languages.go
- ts/typegen/swagger/properties.go
- ts/typegen/swagger/swagger_test.go
- ts/typegen/swagger/testdata/two-arrays-swagger.json
This fixes an issue where the name of the Typescript type for an array entry always ended up being named `Item`. This causes problem when an object in the swagger document has more then one field with type array.
It also fixes some linter issues.
Fixes: https://github.com/GoogleContainerTools/kpt/issues/3686
> Fix naming collisions in generated typescript with two arrays in same object

- ts/scripts/publish-bins.sh
I think the repo was reorganized at some point and this updates the script to point to the new paths for the typegen artifacts.
> Fix bins upload script to reference the correct path
